### ISSUE TITLE
能否适配双栏模式，

### ISSUE THREAD

**Issue by geekhuashan** [Eve-Sama/weread-web-extension#7]
能让界面撑满整个页面，让文字尽量多些

**Comment by geekhuashan** [comment]
但是中间的读书框依然没有增大啊，调节比例不起作用啊
![image](https://github.com/Eve-Sama/weread-web-extension/assets/47098938/12af7fa5-e17a-4816-bf34-68eb0d6b7e0d)

**Comment by Eve-Sama** [comment]
<img width="1920" alt="图片" src="https://github.com/Eve-Sama/weread-web-extension/assets/30228406/cf5e49cc-9096-48b5-aa6e-0cb1310bede0">
我这边是全屏了, 方便查看元素看下 你那边剩余的空白是什么 什么元素的边距吗还是什么

**Comment by geekhuashan** [comment]
完全不会看哈哈哈

**Comment by geekhuashan** [comment]
<div class="wr_canvasContainer"><canvas style="position:absolute;left:70px;top:0px;width:475px;height:781px;" width="950" height="1562"></canvas><canvas style="position:absolute;right:70px;top:0px;width:475px;height:781px;" width="950" height="1562"></canvas></div>


反正我看到中间那个阅读框里面的width 是没有跟着插件调节动而动

**Comment by Eve-Sama** [comment]
> 完全不会看哈哈哈 ctrl + shift + i 点左上角箭头，空白处点不了啊

这个快捷键是什么?

**Comment by Eve-Sama** [comment]
> ```
> <div class="wr_canvasContainer"><canvas style="position:absolute;left:70px;top:0px;width:475px;height:781px;" width="950" height="1562"></canvas><canvas style="position:absolute;right:70px;top:0px;width:475px;height:781px;" width="950" height="1562"></canvas></div>
> ```
> 
> 反正我看到中间那个阅读框里面的width 是没有跟着插件调节动而动

查找一个class为readerChapterContent fontLevel2的元素, 看看他的style上是否有width百分比的设置
<img width="534" alt="图片" src="https://github.com/Eve-Sama/weread-web-extension/assets/30228406/b22f797d-252d-47bc-9746-b9d108ed0ba3">

**Comment by geekhuashan** [comment]
![image](https://github.com/Eve-Sama/weread-web-extension/assets/47098938/af20f3c3-71af-478d-a23c-1df24d4a9231)
![image](https://github.com/Eve-Sama/weread-web-extension/assets/47098938/8804bad2-aa04-453d-a8d0-c0c8ca4016c7)


你说的readerChapterContent fontLevel2 没有的
readerChapterContent fontLevel1 我能搜索到

**Comment by Eve-Sama** [comment]
怀疑可能是账号问题, 也许官方对不同的账号做了不同的处理. 方便给我扫码登录下吗?

**Comment by geekhuashan** [comment]
> 怀疑可能是账号问题, 也许官方对不同的账号做了不同的处理. 方便给我扫码登录下吗?

方便的，怎么联系 我的微信号 geekhuashan
